//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.04 at 02:46:57 AM CEST 
//


package cim2model.cim.map.ipsl.connectors;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;

import cim2model.cim.map.ComponentMap;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *     &lt;extension base="AddressType"&gt;
 *       &lt;attribute name="ConductingEquipment" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TopologicalNode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@XmlRootElement(name = "pwPinMap")
public class PwPinMap extends ComponentMap{
   
    @XmlAttribute(name = "ConductingEquipment", required = true)
    protected String conductingEquipment;
    @XmlAttribute(name = "TopologicalNode", required = true)
    protected String topologicalNode;
       
    /**
     * Gets the value of the conductingEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConductingEquipment() {
        return conductingEquipment;
    }

    /**
     * Sets the value of the conductingEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConductingEquipment(String value) {
        this.conductingEquipment = value;
    }

    /**
     * Gets the value of the topologicalNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopologicalNode() {
        return topologicalNode;
    }

    /**
     * Sets the value of the topologicalNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopologicalNode(String value) {
        this.topologicalNode = value;
    }

    

    @Override
    public String toString()
    {
    	return this.stereotype+ " "+ this._package+" "+ this.name+ 
    			" from "+ this.cimName+ " with id "+ this.rfdId+
    			" having "+ this.conductingEquipment+ " and "+ this.topologicalNode;
    }
}
