//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 08:30:25 PM CET 
//


package cim2modelica.cim.map.openipsl.branches;

import javax.xml.bind.annotation.XmlRootElement;

import cim2modelica.cim.map.ComponentMap;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *      &lt;extension base="ComponentMap"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}mapTerminal" maxOccurs="unbounded"&gt;
 *       &lt;/sequence&gt;
 *      &lt;/extension&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@XmlRootElement(name = "pwLineMap")
public class PwLineMap extends ComponentMap{

}
