//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 11:50:33 AM CET 
//


package cim2model.cim.map.ipsl.machines;

import java.util.List;

import cim2model.cim.map.AttributeMap;

public interface SynchronousMachineMap {

	public String getCimName();
	public String getRdfId();
	public String getRdfResource();
	public String getName();
	public String getPackage();
	public String getStereotype();
	public List<AttributeMap> getAttributeMap();
}
