//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 05:44:11 PM CET 
//


package cim2model.modelica.cimmap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}modelVariableMap" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}terminalMap" maxOccurs="2"/&gt;
 *         &lt;element name="dynamicEquationMap" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}basePowerMap"/&gt;
 *         &lt;element ref="{}baseFrequencyMap"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="cim_mRID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cim_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mo_package" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mo_stereotype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelVariableMap",
    "terminalMap",
    "dynamicEquationMap",
    "basePowerMap",
    "baseFrequencyMap"
})
@XmlRootElement(name = "aCLineSegmentMap")
public class ACLineSegmentMap {

    @XmlElement(required = true)
    protected List<ModelVariableMap> modelVariableMap;
    @XmlElement(required = true)
    protected List<TerminalMap> terminalMap;
    @XmlElement(required = true)
    protected List<String> dynamicEquationMap;
    @XmlElement(required = true)
    protected BasePowerMap basePowerMap;
    @XmlElement(required = true)
    protected BaseFrequencyMap baseFrequencyMap;
    @XmlAttribute(name = "cim_mRID", required = true)
    protected String cimMRID;
    @XmlAttribute(name = "cim_name", required = true)
    protected String cimName;
    @XmlAttribute(name = "mo_package", required = true)
    protected String moPackage;
    @XmlAttribute(name = "mo_stereotype", required = true)
    protected String moStereotype;

    /**
     * Gets the value of the modelVariableMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelVariableMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelVariableMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelVariableMap }
     * 
     * 
     */
    public List<ModelVariableMap> getModelVariableMap() {
        if (modelVariableMap == null) {
            modelVariableMap = new ArrayList<ModelVariableMap>();
        }
        return this.modelVariableMap;
    }

    /**
     * Gets the value of the terminalMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terminalMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerminalMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TerminalMap }
     * 
     * 
     */
    public List<TerminalMap> getTerminalMap() {
        if (terminalMap == null) {
            terminalMap = new ArrayList<TerminalMap>();
        }
        return this.terminalMap;
    }

    /**
     * Gets the value of the dynamicEquationMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dynamicEquationMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDynamicEquationMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDynamicEquationMap() {
        if (dynamicEquationMap == null) {
            dynamicEquationMap = new ArrayList<String>();
        }
        return this.dynamicEquationMap;
    }

    /**
     * Gets the value of the basePowerMap property.
     * 
     * @return
     *     possible object is
     *     {@link BasePowerMap }
     *     
     */
    public BasePowerMap getBasePowerMap() {
        return basePowerMap;
    }

    /**
     * Sets the value of the basePowerMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasePowerMap }
     *     
     */
    public void setBasePowerMap(BasePowerMap value) {
        this.basePowerMap = value;
    }

    /**
     * Gets the value of the baseFrequencyMap property.
     * 
     * @return
     *     possible object is
     *     {@link BaseFrequencyMap }
     *     
     */
    public BaseFrequencyMap getBaseFrequencyMap() {
        return baseFrequencyMap;
    }

    /**
     * Sets the value of the baseFrequencyMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseFrequencyMap }
     *     
     */
    public void setBaseFrequencyMap(BaseFrequencyMap value) {
        this.baseFrequencyMap = value;
    }

    /**
     * Gets the value of the cimMRID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCimMRID() {
        return cimMRID;
    }

    /**
     * Sets the value of the cimMRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCimMRID(String value) {
        this.cimMRID = value;
    }

    /**
     * Gets the value of the cimName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCimName() {
        return cimName;
    }

    /**
     * Sets the value of the cimName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCimName(String value) {
        this.cimName = value;
    }

    /**
     * Gets the value of the moPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoPackage() {
        return moPackage;
    }

    /**
     * Sets the value of the moPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoPackage(String value) {
        this.moPackage = value;
    }

    /**
     * Gets the value of the moStereotype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoStereotype() {
        return moStereotype;
    }

    /**
     * Sets the value of the moStereotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoStereotype(String value) {
        this.moStereotype = value;
    }

}
