//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 03:09:53 PM CET 
//


package cim2model.modelica.cimmap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACLineSegmentMap }
     * 
     */
    public ACLineSegmentMap createACLineSegmentMap() {
        return new ACLineSegmentMap();
    }

    /**
     * Create an instance of {@link ModelVariableMap }
     * 
     */
    public ModelVariableMap createModelVariableMap() {
        return new ModelVariableMap();
    }

    /**
     * Create an instance of {@link TerminalMap }
     * 
     */
    public TerminalMap createTerminalMap() {
        return new TerminalMap();
    }

    /**
     * Create an instance of {@link SvPowerFlowMap }
     * 
     */
    public SvPowerFlowMap createSvPowerFlowMap() {
        return new SvPowerFlowMap();
    }

    /**
     * Create an instance of {@link TopologicalNodeMap }
     * 
     */
    public TopologicalNodeMap createTopologicalNodeMap() {
        return new TopologicalNodeMap();
    }

    /**
     * Create an instance of {@link SvVoltageMap }
     * 
     */
    public SvVoltageMap createSvVoltageMap() {
        return new SvVoltageMap();
    }

    /**
     * Create an instance of {@link BasePowerMap }
     * 
     */
    public BasePowerMap createBasePowerMap() {
        return new BasePowerMap();
    }

    /**
     * Create an instance of {@link BaseFrequencyMap }
     * 
     */
    public BaseFrequencyMap createBaseFrequencyMap() {
        return new BaseFrequencyMap();
    }

}
