//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 08:30:25 PM CET 
//


package cim2model.cim.map.ipsl.branches;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import cim2model.cim.map.ComponentMap;
import cim2model.cim.map.MapTerminal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *      &lt;extension base="ComponentMap"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}mapTerminal" maxOccurs="unbounded"&gt;
 *       &lt;/sequence&gt;
 *      &lt;/extension&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@XmlRootElement(name = "pwLineMap")
public class PwLineMap extends ComponentMap{

    @XmlElement(required = true)
    protected List<MapTerminal> mapTerminal;
 

    /**
     * Gets the value of the mapTerminal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapTerminal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMapTerminal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MapTerminal }
     * 
     * 
     */
    public List<MapTerminal> get_TerminalMap() {
        if (mapTerminal == null) {
            mapTerminal = new ArrayList<MapTerminal>();
        }
        return this.mapTerminal;
    }

}
